### ISSUE TITLE
style.css conflict with CMS layout output 

### ISSUE THREAD

**Issue by samytkhalil** [NorQuest-College/NorQuest-Website#2]
- calling the CSS style.css used in the CMS template 
- I found that some css classes conflict with the CMS layout output such as 
`tbody tr:first-child {
  font-size: 2rem;
  font-weight: 600;
  border-bottom: 0.4rem solid #f58b2e;
  padding: 0;
  }
  tbody tr:first-child td {
    padding: 1.2rem 1.2rem; }

tbody tr:last-child {
  border-bottom: 0.4rem solid #f58b2e; }
`
im attaching two images, the one with the green box is the output with using the style.css

the other one, is the default output without the style.css

![Screenshot 2021-07-28 140425](https://user-images.githubusercontent.com/46852598/127388353-ef62df1a-14a0-4708-8cc3-f26243ec7073.png)
![default-output](https://user-images.githubusercontent.com/46852598/127388532-31b74ce6-a45e-4f6a-86ef-4c8e9d2d5310.png)

**Comment by alfredk** [comment]
Hey @samytkhalil  - If you remove all the `<hr>` that should clean up all the issues you might be seeing. I've removed them all from the markup for the next update later this week. Thanks
