### ISSUE TITLE
Remove Legacy header style link and meta information

### ISSUE THREAD

**Issue by Shaun-Ellithorpe** [NorQuest-College/NorQuest-Website#4]
`<head id="head"><meta charset="utf-8" /><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" /><meta name="viewport" content="width=device-width, initial-scale=1" /><link rel="apple-touch-icon" href="/NorquestCollege/media/images/apple-touch-icon.png" /><link href="//cloud.webtype.com/css/b29ee234-a755-4749-834b-334f61b7c911.css" rel="stylesheet" type="text/css" />`

**Comment by samytkhalil** [comment]
fixed
