### ISSUE TITLE
Preconnect and DNS-prefetch for 3rd party scripts/stylesheets

### ISSUE THREAD

**Issue by Shaun-Ellithorpe** [NorQuest-College/NorQuest-Website#7]
Add in Preconnect and DNS-Prefetch to head for any 3rd party scripts and stylesheets

&#x3C;link rel=&#x22;preconnect&#x22; href=&#x22;https://use.typekit.net &#x22; crossorigin&#x3E;
&#x3C;link rel=&#x22;dns-prefetch&#x22; href=&#x22;https://use.typekit.net &#x22; &#x3E;
&#x3C;link rel=&#x22;preconnect&#x22; href=&#x22;https://kit.fontawesome.com &#x22; crossorigin&#x3E;
&#x3C;link rel=&#x22;dns-prefetch&#x22; href=&#x22;https://kit.fontawesome.com &#x22;&#x3E;

**Comment by samytkhalil** [comment]
added to main master template
